### ISSUE TITLE
Mar 01 Papers

### ISSUE THREAD

**Issue by anastasia-tsvetkova** [grburgess/awesome-reading-group#14]
### Paper Tile

link

abstract

**Comment by anastasia-tsvetkova** [comment]
**A peculiar hard X-ray counterpart of a Galactic fast radio burst**

https://www.nature.com/articles/s41550-020-01265-0.pdf

Fast radio bursts (FRBs) are bright, millisecond-scale radio flashes of unknown physical origin. Young, highly magnetized, isolated neutron stars—magnetars—have been suggested as the most promising candidates for FRB progenitors owing to their energetics and high X-ray flaring activity. Here we report the detection with Konus-Wind of a hard X-ray event of 28 April 2020 temporally coincident with a bright, two-peak radio burst in the direction of Galactic magnetar SGR 1935+2154, with properties remarkably similar to those of FRBs. We show that the two peaks of the double-peaked X-ray burst coincide in time with the radio peaks and infer a common source and the association of these phenomena. An unusual hardness of the X-ray spectrum strongly distinguishes the 28 April event among multiple ‘ordinary’ flares from SGR 1935+2154. A recent non-detection of radio emission from about 100 typical soft bursts from SGR 1935+2154 favours the idea that bright, FRB-like magnetar signals are associated with rare, hard-spectrum X-ray bursts. The implied rate of these hard X-ray bursts (~0.04 yr^-1 magnetar-1) appears consistent with the rate estimate of SGR 1935+2154-like radio bursts (0.007–0.04 yr-1  magnetar^-1). 

Comment: The first simultaneous detection of an FRB from a magnetar in the Milky Way and its high-energy counterpart.

**Comment by fberlato** [comment]
**A tidal disruption event coincident with a high-energy neutrino**

https://www.nature.com/articles/s41550-020-01295-8

Cosmic neutrinos provide a unique window into the otherwise hidden mechanism of particle acceleration in astrophysical objects. The IceCube Collaboration recently reported the likely association of one high-energy neutrino with a flare from the relativistic jet of an active galaxy pointed towards the Earth. However a combined analysis of many similar active galaxies revealed no excess from the broader population, leaving the vast majority of the cosmic neutrino flux unexplained. Here we present the likely association of a radio-emitting tidal disruption event, AT2019dsg, with a second high-energy neutrino. AT2019dsg was identified as part of our systematic search for optical counterparts to high-energy neutrinos with the Zwicky Transient Facility. The probability of finding any coincident radio-emitting tidal disruption event by chance is 0.5%, while the probability of finding one as bright in bolometric energy flux as AT2019dsg is 0.2%. Our electromagnetic observations can be explained through a multizone model, with radio analysis revealing a central engine, embedded in a UV photosphere, that powers an extended synchrotron-emitting outflow. This provides an ideal site for petaelectronvolt neutrino production. Assuming that the association is genuine, our observations suggest that tidal disruption events with mildly relativistic outflows contribute to the cosmic neutrino flux.

**Comment by cescalara** [comment]
### Probabilistic Association of Transients to their Hosts (PATH)

https://arxiv.org/abs/2102.10627

We introduce a new method to estimate the probability that an extragalactic transient source is associated with a candidate host galaxy. This approach relies solely on simple observables: sky coordinates and their uncertainties, galaxy fluxes and angular sizes. The formalism invokes Bayes' rule to calculate the posterior probability P(O_i|x) from the galaxy prior P(O), observables x, and an assumed model for the true distribution of transients in/around their host galaxies. Using simulated transients placed in the well-studied COSMOS field, we consider several agnostic and physically motivated priors and offset distributions to explore the method sensitivity. We then apply the methodology to the set of 13~fast radio bursts (FRBs) localized with an uncertainty of several arcseconds. Our methodology finds nine of these are securely associated to a single host galaxy, P(O_i|x)>0.95. We examine the observed and intrinsic properties of these secure FRB hosts, recovering similar distributions as previous works. Furthermore, we find a strong correlation between the apparent magnitude of the securely identified host galaxies and the estimated cosmic dispersion measures of the corresponding FRBs, which results from the Macquart relation. Future work with FRBs will leverage this relation and other measures from the secure hosts as priors for future associations. The methodology is generic to transient type, localization error, and image quality. We encourage its application to other transients where host galaxy associations are critical to the science, e.g. gravitational wave events, gamma-ray bursts, and supernovae. We have encoded the technique in Python on GitHub: this https URL.

**Comment by grburgess** [comment]
### A Cosmological Fireball with Thirty-Percent Gamma-Ray Radiative Efficiency

https://www.researchsquare.com/article/rs-231408/v1

Gamma-ray bursts (GRBs) are the most powerful explosions in the universe. The composition of the jets is, however, subject to debate\cite{Peer2015,Zhang2018}. Whereas the traditional model invokes a relativistic matter-dominated fireball with a bright photosphere emission component\cite{Meszaros2000}, the lack of the detection of such a component in some GRBs\cite{Abdo2009} has led to the conclusion that GRB jets may be Poynting-flux-dominated\cite{Zhang2009}. Furthermore, how efficiently the jet converts its energy to radiation is poorly constrained. A definitive diagnosis of the GRB jet composition and measurement of GRB radiative efficiency requires high-quality prompt emission and afterglow data, which has not been possible with the sparse observations in the past. Here we report a comprehensive temporal and spectral analysis of the TeV-emitting bright GRB 190114C. Its fluence is one of the highest of all GRBs detected so far, which allows us to perform a high-significance study on the prompt emission spectral properties and their variations down to a very short timescale of about 0.1 s. We identify a clear thermal component during the first two prompt emission episodes, which is fully consistent with the prediction of the fireball photosphere model. The third episode of the prompt emission is consistent with synchrotron radiation from the deceleration of the fireball. This allows us to directly dissect the fireball energy budget in a parameter-independent manner\cite{Zhang2021} and robustly measure a nearly $30\%$ radiative efficiency for this GRB. The afterglow microphysics parameters can be also well constrained from the data. GRB 190114C, therefore, exhibits the evolution of a textbook-version relativistic fireball, suggesting that fireballs can indeed power at least some GRBs with high efficiency.

#### Comments:

The analysis is so beautiful I could have written it myself.
