### ISSUE TITLE
22 March Paper

### ISSUE THREAD

**Issue by BjoernBiltzinger** [grburgess/awesome-reading-group#17]
### Constraints on the antistar fraction in the Solar system neighborhood from the 10-years Fermi Large Area Telescope gamma-ray source catalog

https://arxiv.org/abs/2103.10073

It is generally taken for granted that our Universe is free of antimatter objects and domains. This certitude has recently been challenged by the possible detection of anti-helium nuclei by AMS-02. Should the observation be confirmed, the existence of nearby antistars would make a plausible hypothesis to explain the origin of the antinuclei. In this paper we use the 10-years \F Large Area Telescope (LAT) gamma-ray source catalog to set constraints on the abundance of antistars around the Sun. We identify in the catalog 14 antistar candidates not associated with any objects belonging to established gamma-ray source classes and with a spectrum compatible with baryon-antibaryon annihilation. We use them along with an estimate of the LAT sensitivity to antistars to set upper limits on the local antistar fraction f∗¯ with respect to normal stars. We provide parametric limits as a function of the closest antistar mass, velocity, and surrounding matter density. We also employ a novel Monte~Carlo method to set limits for a few hypotheses about the antistar population. For a population with properties equivalent to those of regular stars concentrated in the Galactic disk we obtain f∗¯<2.5×10−6 at 95\% confidence level, which is 20 times more constraining than limits previously available. For a primordial population of antistars distributed in the Galactic halo we obtain new local upper limits which decrease as a function of antistar mass M from f∗¯<0.2 at 95\% confidence level for M=1M⊙ to f∗¯<1.6×10−4 at 95\% confidence level for M=10M⊙. By combining these limits with existing microlensing constraints for lighter objects in the Magellanic clouds, we infer that a primordial population of halo antistars must have a density lower than O(10−5pc−3) to O(10−2pc−3) depending on their masses. Our limits can constrain models for the origin and propagation of antinuclei in cosmic rays. 

#### Comments:

Well, sounds interesting.

**Comment by grburgess** [comment]
We also have some content from the week's before.

**Comment by grburgess** [comment]
## A metal rich molecular cloud surrounds GRB 050904 at redshift 6.3

https://arxiv.org/abs/astro-ph/0611305


GRB050904 is the gamma-ray burst with the highest measured redshift. We performed time resolved X-ray spectroscopy of the late GRB and early afterglow emission. We find robust evidence for a decrease with time of the soft X-ray absorbing column. We model the evolution of the column density due to the flash ionization of the GRB and early afterglow photons. This allows us to constrain the metallicity and geometry of the absorbing cloud. We conclude that the progenitor of GRB050904 was a massive star embedded in a dense metal enriched molecular cloud with Z~0.03 Z_solar. This is the first local measurement of metallicity in the close environment of a GRB and one of the highest redshift metallicity measurements. We also find that the dust associated with the cloud cannot be similar to that of our Galaxy but must be either sizably depleted or dominated by silicate grains. We discuss the implications of these results for GRB progenitors and high redshift star formation.

#### Comments: 

related to gas.

**Comment by grburgess** [comment]
## X-ray absorption evolution in gamma-ray bursts: intergalactic medium or evolutionary signature of their host galaxies 

https://academic.oup.com/mnras/article/431/4/3159/1141602

The intrinsic X-ray emission of gamma-ray bursts (GRBs) is often found to be absorbed over and above the column density through our own Galaxy. The extra component is usually assumed to be due to absorbing gas lying within the host galaxy of the GRB itself. There is an apparent correlation between the equivalent column density of hydrogen, NH,intrinsic (assuming it to be at the GRB redshift), and redshift, z, with the few z > 6 GRBs showing the greatest intrinsic column densities. We investigate the NH, intrinsic-z relation using a large sample of Swift GRBs, as well as active galactic nuclei and quasar samples, paying particular attention to the spectral energy distributions of the two highest redshift GRBs. Various possible sample biases and systematics that might produce such a correlation are considered, and we conclude that the correlation is very likely to be real. This may indicate either an evolutionary effect in the host galaxy properties, or a contribution from gas along the line of sight, in the diffuse intergalactic medium (IGM) or intervening absorbing clouds. Employing a more realistic model for IGM absorption than in previous works, we find that this may explain much of the observed opacity at z ≳ 3 providing it is not too hot, likely between 105 and 106.5 K, and moderately metal enriched, Z ∼ 0.2 Z⊙. This material could therefore constitute the warm–hot intergalactic medium. However, a comparable level of absorption is also expected from the cumulative effect of intervening cold gas clouds, and given current uncertainties it is not possible to say which, if either, dominates. At lower redshifts, we conclude that gas in the host galaxies must be the dominant contributor to the observed X-ray absorption.

#### Comments: 

more gas
