### ISSUE TITLE
Apr 26 papers

### ISSUE THREAD

**Issue by grburgess** [grburgess/awesome-reading-group#21]
### Black Swans in Astronomical Data

https://arxiv.org/abs/2104.07693

Astronomy has always been propelled by the discovery of new phenomena lacking precedent, often followed by new theories to explain their existence and properties. In the modern era of large surveys tiling the sky at ever high precision and sampling rates, these serendipitous discoveries look set to continue, with recent examples including Boyajian's Star, Fast Radio Bursts and `Oumuamua. Accordingly, we here look ahead and aim to provide a statistical framework for interpreting such events and providing guidance to future observations, under the basic premise that the phenomenon in question stochastically repeat at some unknown, constant rate, λ. Specifically, expressions are derived for 1) the a-posteriori distribution for λ, 2) the a-posteriori distribution for the recurrence time, and, 3) the benefit-to-cost ratio of further observations relative to that of the inaugural event. Some rule-of-thumb results for each of these are found to be 1) λ<{0.7,2.3,4.6}t−11 to {50,90,95}% confidence (where t1= time to obtain the first detection), 2) the recurrence time is t2<{1,9,99}t1 to {50,90,95}% confidence, with a lack of repetition by time t2 yielding a p-value of 1/[1+(t2/t1)], and, 3) follow-up for ≲10t1 is expected to be scientifically worthwhile under an array of differing assumptions about the object's intrinsic scientific value. We apply these methods to the Breakthrough Listen Candidate 1 signal and tidal disruption events observed by TESS.

#### Comments:

This is stupid.

**Comment by grburgess** [comment]
### A Bayesian Approach to Modelling Multi-Messenger Emission from Blazars using Lepto-Hadronic Kinetic Equations

https://arxiv.org/abs/2006.01543

Blazar TXS 0506+056 is the main candidate for a coincident neutrino and gamma-ray flare event. In this paper, we present a detailed kinetic lepto-hadronic emission model capable of producing a photon and neutrino spectrum given a set of parameters. Our model includes a range of large-scale geometries and both dynamical and steady-state injection models for electrons and protons. We link this model with a Markov Chain Monte Carlo sampler to obtain a powerful statistical tool that allows us to both fit the Spectral Energy Distribution and study the probability density functions and correlations of the parameters. Assuming a fiducial neutrino flux, we demonstrate how multi-messenger observations can be modelled jointly in a Bayesian framework. We find the best parameters for each of the variants of the model tested and report on their cross-correlations. Additionally, we confirm that reproducing the neutrino flux of TXS 0506+056 requires an extreme proton to electron ratio either in the local acceleration process or from external injection.

#### Comments:

Regardless of the title... this is not Bayesian at all. However, probably the only proof needed to show the TXS neutrino is NOT real.

**Comment by cescalara** [comment]
### Multi-messenger Implications of Sub-PeV Diffuse Galactic Gamma-Ray Emission

https://arxiv.org/abs/2104.09491

The diffuse Galactic gamma-ray flux between 0.1 and 1 PeV has recently been measured by the Tibet ASγ Collaboration. The flux and spectrum are consistent with the decay of neutral pions from hadronuclear interactions between Galactic cosmic rays and the interstellar medium (ISM). We derive the flux of the Galactic diffuse neutrino emission from the same interaction process that produces the gamma rays. Our calculation accounts for the effect of gamma-ray attenuation inside the Milky Way and uncertainties due to the spectrum and distribution of cosmic rays, gas density, and infrared emission of the ISM. We find that the contribution from the Galactic plane to the all-sky neutrino flux is ≲5−10% around 100 TeV. The Galactic and extragalactic neutrino intensities are comparable in the Galactic plane region. Our results are consistent with the upper limit reported by the IceCube and ANTARES Collaborations, and predict that next-generation neutrino experiments may observe the Galactic component. We also show that the Tibet ASγ data imply either an additional component in the cosmic-ray nucleon spectrum or contribution from discrete sources, including Pevatrons such as superbubbles and hypernova remnants, and PeV electron accelerators. Future multi-messenger observations between 1 TeV and 1 PeV are crucial to decomposing the origin of sub-PeV gamma rays.

#### Comments:

Relevant for the Galactic interpretation of IceCube neutrinos.

**Comment by grburgess** [comment]
### Gamma Ray Burst studies with THESEUS

https://arxiv.org/abs/2104.10448

Gamma-ray Bursts (GRBs) are the most powerful transients in the Universe, over-shining for a few seconds all other γ-ray sky sources. Their emission is produced within narrowly collimated relativistic jets launched after the core-collapse of massive stars or the merger of compact binaries. THESEUS will open a new window for the use of GRBs as cosmological tools by securing a statistically significant sample of high-z GRBs, as well as by providing a large number of GRBs at low-intermediate redshifts extending the current samples to low luminosities. The wide energy band and unprecedented sensitivity of the Soft X-ray Imager (SXI) and X-Gamma rays Imaging Spectrometer (XGIS) instruments provide us a new route to unveil the nature of the prompt emission. For the first time, a full characterisation of the prompt emission spectrum from 0.3 keV to 10 MeV with unprecedented large count statistics will be possible revealing the signatures of synchrotron emission. SXI spectra, extending down to 0.3 keV, will constrain the local metal absorption and, for the brightest events, the progenitors' ejecta composition. Investigation of the nature of the internal energy dissipation mechanisms will be obtained through the systematic study with XGIS of the sub-second variability unexplored so far over such a wide energy range. THESEUS will follow the spectral evolution of the prompt emission down to the soft X-ray band during the early steep decay and through the plateau phase with the unique ability of extending above 10 keV the spectral study of these early afterglow emission phases.

#### Comments:

Nothing amazing here except lack of citation and bad population Monte Carlo.
