### ISSUE TITLE
Jun 14  Paper

### ISSUE THREAD

**Issue by grburgess** [grburgess/awesome-reading-group#27]
### The slope of the low energy spectrum of Gamma-Ray Burst prompt emission

https://arxiv.org/abs/2106.03868v1

Gamma-ray Bursts (GRBs) prompt emission spectra are often fitted with the empirical ''Band" function, namely two power laws smoothly connected. The typical slope of the low energy (sub-MeV) power law is αB≃−1. In a small fraction of long GRBs this power law splits into two components such that the spectrum presents, in addition to the typical ∼ MeV νFν peak, a break at the order of a few keV or hundreds keV. The typical power law slopes below and above the break are -0.6 and -1.5 respectively. If the break is a common feature, the value of αB could be an ''average'' of the spectral slopes below and above the break in GRBs fitted with Band function. We analyze the spectra of 27 (9) bright long (short) GRBs detected by the Fermi satellite finding a low energy break between 80 keV and 280 keV in 12 long GRBs, but in none of the short events. Through spectral simulations we show that if the break is moved closer (farther) to the peak energy a relatively harder (softer) αB is found by fitting the simulated spectra with the Band function. The hard average slope αB≃−0.38 found in short GRBs suggests that the break is close to the peak energy. We show that for 15 long GRBs best fitted by the Band function only, the break could be present, but it is not identifiable in the Fermi/GBM spectrum, because either at low energies, close to the detector limit for relatively soft αB≲−1, or in the proximity of the energy peak for relatively hard αB≳−1. A spectrum with two breaks could be typical of GRB prompt emission, though hard to identify with current detectors. Instrumental design such that conceived for the THESEUS space mission, extending from 0.3 keV to several MeV and featuring a larger effective area with respect to Fermi/GBM, can reveal a larger fraction of GRBs with a spectral energy break.

**Comment by BjoernBiltzinger** [comment]
# Probing the evolution of the EBL photon density out to z∼1viaγ-ray propagation measurements with Fermi

https://arxiv.org/abs/2105.14293

The redshift (z) evolution of the Extragalactic Background Light (EBL) photon density is very important to understand the history of cosmological structure formation of galaxies and stars since the epoch of recombination. The EBL photons with the characteristic spectral energy distribution ranging from ultraviolet/optical to far-infrared provide a major source of opacity of the Universe to the GeV-TeV γ-rays travelling over cosmological distances. The effect of the EBL is very significant through γγ→e−e+ absorption process on the propagation of the γ-ray photons with energy E> 50 GeV emitted from the sources at z∼1. This effect is characterized by the optical depth (τ) which strongly depends on E, z and density of the EBL photons. The proper density of the EBL photons increases with z due to expansion of the Universe whereas evolution of radiation sources contributing to the EBL leads to a decrease in the density with increasing z. Therefore, the resultant volumetric evolution of the EBL photon density is approximated by a modified redshift dependence. In this work, we probe evolution of the EBL photon density predicted by two prominent models using cosmic gamma-ray horizon (τ(E,z)= 1) determined by the measurements from the \emph{Fermi}-Large Area Telescope (LAT) observations. The modified redshift dependence of the EBL photon density is optimized for a given EBL model by estimating the same gamma-ray horizon as predicted by the \emph{Fermi}-LAT observations. We further compare the optical depth estimates in the energy range E= 4 GeV-1 TeV and redshift range z=0.01−1 from the \emph{Fermi}-LAT observations with the values derived from the two EBL models to further constrain the evolution of the EBL photon density in the z ∼1 Universe.
