### ISSUE TITLE
Papers Voting Nov 23

### ISSUE THREAD

**Issue by grburgess** [grburgess/awesome-reading-group#3]
### What determines the structure of short gamma-ray burst jets?

https://arxiv.org/abs/2011.06729

The discovery of GRB 170817A, the first unambiguous off-axis short gamma-ray burst arising from a neutron star merger, has challenged our understanding of the angular structure of relativistic jets. The late afterglow of GRB 170817A has been described by a structured jet seen slightly off-axis (at an observer angle of ≈20∘--30∘). Studies of the jet dynamics and propagation usually assume that the jet is ejected from the central engine with a top-hat structure and its final structure, which determines the observed light curve and spectra, is primarily regulated by the interaction with the nearby environment. However, relativistic jets are expected to be produced with a structure that is more complex than a simple top-hat, as shown by global accretion simulations. In this work, we present results of numerical simulations of short GRBs launched with a wide range of initial structures, durations, luminosities, and ejection time histories. We follow the interaction of the jet with the pre-collapse, merger remnant wind and compute its final structure at distances ≳1011~cm from the central engine. We show that the final jet structure, as well as the resulting afterglow emission (at much larger distances), depend strongly on the initial structure of the jet, its luminosity and duration. We find that the initial structure at the jet is preserved for long-lasting SGRBs, while it is strongly modified for jets barely making their way through the wind. This illustrates the importance of combining the results of global simulations with propagation studies in order to better predict the expected afterglow signatures from neutron star mergers. Structured jets provide a reasonable description of the GRB 170817A afterglow emission with an off-axis angle θobs≈22.5∘ while top-hat jets do not.

**Comment by grburgess** [comment]
## Differential Source Count for Gamma Ray Bursts

https://arxiv.org/abs/2011.03945

In this work, we revisit our earlier attempt to quantify the intrinsic luminosity function N(L)dL of Gamma Ray Bursts (GRBs) using observational constraints on the distribution of intrinsic luminosities. In our earlier work, the median luminosity Lmedian(z) was calculated, as a function of redshift, of beamed, identical, detectable sources of known redshifts, and compared with the luminosities of nearby GRBs of known redshift. In this paper, we constrain N(L)dL from the observed flux distribution N(F)dF by calculating the expected N(F) from a sample of GRBs with {\it unknown} redshift. We compare our theoretical expectations from a physical model with Fermi GBM data and thus constrain the angular emission profile of the GRBs. We find that at wide angles, N(L) is consistent with having a subluminous component, but that it is inconsistent with {\it purely} on-axis viewing.

### Comments:

Could be interesting to talk about the issues with this.

**Comment by BjoernBiltzinger** [comment]
### Electromagnetic signatures of relativistic explosions in AGN disk

https://arxiv.org/pdf/2011.08873.pdf

The disks of Active Galactic Nuclei (AGNs), traditionally studied as the feeders of the supermassive blackholes (SMBHs) at their centers, have recently triggered a lot of interest also as hosts to massive stars and hencetheir neutron star (NS) and black hole (BH) remnants.  Migration traps and gas torques in these disks favorbinary formation and enhance the rate of compact object mergers. In these environments both long gamma-raybursts (GRBs) from the death of massive stars and short GRBs from NS-NS and NS-BH mergers are expected.However, their properties in the unique environments of AGN disks have never been studied. Here we show thatGRBs in AGNs can display unique features, owing to the unusual relative position of the shocks that characterizethe burst evolution and the Thomson photosphere of the AGN disk.  In dense environments, for example, theexternal shock develops before the internal shocks, leading to prompt emission powered by a relativistic reverseshock.  The transient’s time evolution is also compressed,  yielding afterglow emission that is much brighterand peaks much earlier than for GRBs in the interstellar medium.   Additionally,  in regions of the disk thatare sufficiently dense and extended, the light curves are dominated by diffusion, since the fireball is trappedinside the disc photosphere. These diffusion-dominated transients emerge on timescales of days in disks aroundSMBHs of∼106M to years for SMBHs of∼108M. Finally, a large fraction of events, especially in AGNswith SMBHs.107M, display time-variable absorption in the X-ray band.

**Comments:**

GRBs from AGN disks. Sounds interesting.

**Comment by grburgess** [comment]
### Gaussian Process Modeling Fermi-LAT γ-ray Blazar Variability: A Sample of Blazars with γ-ray Quasi-periodicities
https://arxiv.org/abs/2011.10186

Blazar variability may be driven by stochastic processes. On the other hand, quasi-periodic oscillation (QPO) behaviors are recently reported to be detected in Fermi-LAT data of blazars. However, the significances of these QPO signals given by traditional Fourier-like methods are still questioned. We analyze γ-ray light curves of the QPO blazars with two Gaussian process methods, CARMA and celerite, to examine the appropriateness of Gaussian processes for characterizing γ-ray light curves of blazars and the existence of the reported QPOs. We collect a sample of 27 blazars with possible γ-ray periodicity and generate their ∼11 years Fermi-LAT light curves. We apply the Gaussian process models to the γ-ray light curves, and build their intrinsic power spectral densities (PSDs). The results show that in general the γ-ray light curves can be characterized by CARMA and celerite models, indicating that γ-ray variabilities of blazars are essentially Gaussian processes. The resulting PSDs are generally the red noise shapes with slopes between −0.6 and −1.7. Possible evidence for the γ-ray QPOs in PKS 0537−441 and PG 1553+113 are found in the Gaussian process modelings.

#### Comments:
 I only want to point out that how bad software, methodology, and a poor understanding of what you are doing leads to... this.
