### ISSUE TITLE
Dec 14 Paper

### ISSUE THREAD

**Issue by grburgess** [grburgess/awesome-reading-group#6]
### Revisiting the Redshift Evolution of GRB Luminosity Correlation with PAge Approximation

https://arxiv.org/abs/2012.02474

The correlation between the peak spectra energy and the equivalent isotropic energy of long gamma-ray bursts (GRBs), the so-called Amati relation, is often used to constrain the high-redshift Hubble diagram of the universe. Assuming Lambda cold dark matter (ΛCDM) cosmology, Wang et al. found a ≳3σ tension in the data-calibrated Amati coefficients between low- and high-redshift GRB samples. To test whether beyond-ΛCDM cosmology could resolve the tension, we use PAge approximation, an almost model-independent cosmology framework to revisit the redshift evolution of Amati relation. We find that the low- and high-redshift tension of Amati relation remains at ∼3σ level in the PAge framework. Thus, for the broad class of models covered by PAge approximation, caution needs to be taken for the use of GRBs as high-redshift distance indicators.

#### Comments:

A mind is a terrible thing to waste

**Comment by JochenGreiner** [comment]
### Identification of GRB precursors in Fermi-GBM burst

[https://arxiv.org/2004.03246](url)

We  present  an  analysis  of  more  than  11  years  of  Fermi-GBM  data  in  which  217  Gamma-RayBursts (GRBs) are found for which their main burst is preceded by a precursor flash.  We find thatshort GRBs (<2 s) are∼10 times less likely to produce a precursor than long GRBs.  The quiescenttime profile,  given by the time between the precursor and the main burst,  is well described by adouble  Gaussian  distribution,  indicating  that  the  observed  precursors  have  two  distinct  physicalprogenitors.  The light curves of the identified precursor GRBs are publicly available in an online catalog (https://icecube.wisc.edu/~grbweb_public/Precursors.html)

**Comment by cescalara** [comment]
### Bayesian Time-Resolved Spectroscopy of Multi-Pulsed GRBs: Variations of Emission Properties amongst Pulses

https://arxiv.org/abs/2012.03038

Gamma-ray bursts (GRBs) are highly variable and exhibit strong spectral evolution. In particular, the emission properties vary from pulse to pulse in multi-pulsed bursts. Here, we present a time-resolved Bayesian spectral analysis of a compilation of GRB pulses observed by the {\it Fermi}/Gamma-ray Burst Monitor (GBM). The pulses are selected to have at least four time-bins with a high statistical significance, which ensures that the spectral fits are well determined and that spectral correlations can be established. The sample consists of 39 bursts, 117 pulses, and 1228 spectra. We confirm the general trend that pulses become softer over time, with mainly the low-energy power-law index α becoming smaller. A few exceptions from this trend exist with the hardest pulse occurring at late times. The first pulse in a burst is clearly different from the later pulses: 3/4 of them violate the synchrotron line-of-death, while around half of them significantly prefer photospheric emission. These fractions decrease for subsequent pulses. We also find that in 2/3 of the pulses the spectral parameters (α and peak energy) track the light-curve variations. This is a larger fraction compared to what is found in previous samples. In conclusion, emission compatible with the GRB photosphere is typically found close to the trigger time, while the chance of detecting synchrotron emission is greatest at late times. This allows for coexistence of emission mechanisms at late times.

#### Comments

A classic Liang paper with 111 pages

**Comment by cescalara** [comment]
### Tracing dark energy history with gamma ray bursts

https://arxiv.org/abs/2012.03392

Observations of gamma-ray bursts up to z∼9 are best suited to study the possible evolution of the Universe equation of state at intermediate redshifts. We apply the Combo-relation to a sample of 174 gamma ray bursts to investigate possible evidence of evolving dark energy parameter w(z). We first build a gamma ray burst Hubble's diagram and then we estimate the set (Ωm, ΩΛ) in the framework of flat and non-flat ΛCDM paradigm. We then get bounds over the wCDM model, where w is thought to evolve with redshift, adopting two priors over the Hubble constant in tension at 4.4-σ, i.e. H0=(67.4±0.5) km/s/Mpc and H0=(74.03±1.42) km/s/Mpc. We show our new sample provides tighter constraints on Ωm since at z≤1.2 we see that w(z) agrees within 1σ with the standard value w=−1. The situation is the opposite at larger z, where gamma ray bursts better fix w(z) that seems to deviate from w=−1 at 2-σ and 4-σ level, depending on the redshift bins. In particular, we investigate the w(z) evolution through a piecewise formulation over seven redshift intervals. From our fitting procedure we show that at z≥1.2 the case w<−1 cannot be fully excluded, indicating that dark energy's influence is not negligible at larger z. We confirm the Combo relation as a powerful tool to investigate cosmological evolution of dark energy. Future space missions will significantly enrich the gamma ray burst database even at smaller redshifts, improving de facto the results discussed in this paper.

#### Comments

Could be interesting following on from discussions last week

**Comment by cescalara** [comment]
### Energetics of ultrahigh-energy cosmic-ray nuclei

https://arxiv.org/abs/2012.03122

Energetics of the ultrahigh-energy cosmic rays (UHECRs) generated in the universe is crucial for pinning down their candidate sources. Using the recent Auger data on UHECR spectra, we calculate the UHECR energy generation rate density for different species of nuclei at the injection, considering intermediate and heavy nuclei as well as protons, through scanning over source parameters on the spectral index, maximum energy and redshift evolution. We find the resulting UHECR energy generation rate density to be ≈(0.2−2)×1044 erg Mpc−3 yr−1 at 1019.5 eV with a nontrivial dependence on the spectral index. Nuclei other than protons and irons favor hard spectral indices at the injection, and the required value of energy budget is smaller for intermediate nuclei. Given significant uncertainties in hadronic interaction models and astrophysical models for the Galactic-extragalactic transition, our results can be regarded as conservative. The composition data on Xmax give additional constraints, but the results are consistent within the model uncertainties.

#### Comments

I will read this in case anyone is interested

**Comment by BjoernBiltzinger** [comment]
### A first-principle simulation of blast wave emergence at the photosphere of a neutron star merger

https://arxiv.org/abs/2012.01798

We present the first ab initio simulation of a radiation-mediated shock emerging at the photosphere of a relativistic outflow. The simulation is performed using our code radshock that follows fluid dynamics coupled to time-dependent radiative transfer, calculated with the Monte-Carlo method. We use the code to examine the radiative blast wave emerging from neutron star merger GW~170817. It was previously proposed that the merger ejected a dark, relativistically expanding, homologous envelope, and then an explosion inside the envelope produced the observed gamma-ray burst GRB~170817A. Our simulation demonstrates how the shock wave generates radiation as it propagates through the envelope, approaches its photosphere, releases the radiation, and collapses, splitting into two collisionless shocks of a microscopic thickness. We find the light curve and the spectral evolution of the produced gamma-ray burst; both are similar to the observed GRB~170817A.
